TRUTH = (
    "Wish list tahun ini apa?",
    "kalau dikasih kesempatan ketemu orang,siapa yang mau kamu temukan?",
    "teman yang nyebelin siapa?",
    "pengalaman berharga yang ga pernah dilupakan apa?",
    "apakah kalian pernah merasa insecure,coba ceritakan?",
    "sehari BAB berapa kali?",
    "sahabat lawan jenis yang menurut kamu bakalan cocok jadi pacar kamu siapa?",
    "hal apa yang membuat kamu galau?",
    "ketika pasangan kamu marah,ada atau tidak ke inginan kamu buat marah balik?",
    "hal apa yang membuat kamu kesepian?",
    "kenapa kamu ingin berpasangan dengan pasangan mu sekarang?",
    "hal-hal apa yang membuat pasangan kamu bete sama kamu?",
    "coba deskripsikan pasangan kamu yang sekarang?",
    "ceritakan mimpi terkonyol mu?",
    "apakah kamu pernah BAB dalam celana,coba ceritakan?",
    "apa nawa hewan peliharaanmu? jika tidak punya,hewan apa yang ingin kamu adopsi?",
)

DARE = (
    "prank pacar bilang kalau kamu hamil,jangan lupa ss"
    "kasih lagu kesukaan kalian ke crush atau pacar kalian",
    "bilang ke roomchat orang random,kamu pipiss di celana",
    "voice note kentut ke group atau gc kalian",
    "telfon orang random lalu bilang kenapa telfon",
    "ganti ava jadi warna pink soft",
    "rate kegantengan crush atau mantan di ch kalian",
    "tag orang di gc no 17 bilang bahwa kamu hamil anak mu mas",
    "jujur sama crush atau pasangan kamu kalau kalian pernah BAB di celana",
    "prank mantan kamu bilang kalau kamu gamon",
    "confes ke rush kamu sekarang",
    "tidak berkata kasar selama 1 hari",
    "tag orang yang paling kamu benci,kalau tidak mau jawab silahkan click /truth",
    "pasang ava monyet selama seminggu",
    "ucapin hbd ke orang random",
    "sebutin inisial crush",
    "tulis dikertas 'aku sayang kamu' lalu foto kirim ke orang tersayang",
    "pakai dn 'AKU ANAK HILANG' selama satu jam",
    "nyanyikan reff lagu yang terakhir kamu dengarkan",
    "ketik pakai bahasa daerah masing masing selama satu jam",
    "gombalin crush kamu",
    "ss game yang ada di hp mu",
    "nyanyiin lagu 'HAI TAYO' ke orang random",
    "tulis puisi aneh di gc kalian",
    "tipe ideal cowo/cewe idaman kamu di virtual maupun in real life",
    "kasih foto bunga ke teman terbaikmu",
    "typing alay+jamet seharian penuh (1x24 jam)",
    "bilang ily ke pacar/crush lewat vn",
    "typing capslock selama permainan selesai",
    "kasih lagu kesukaan kalian ke crush/pacar",
    "nyanyi pakai suara cempreng",
    "bilang 'KAMU CANTIK BANGETT' ke cowo",
    "panggil pacar kamu menggunakan nama dia selama sehari",
    "bilang ke orang yang kamu sayang bahwa dia berharga banget buat kamu",
    "Put as many snacks into your mouth at once as you can",
    "post about pacar kamuu di ch",
    "pake ava pesulap merah selama 1 hari",
    "drop lagu/quotes terus tag member gc yang menurut kamu relate dengan mereka",
    "bilang ke orang random bahwa 'aku baru saja dapat kabar bahwa kita anak kembar yang terpisahkan dan aku oprasi plastik dan ini hal yang paling ciuss",
    "Send a screenshot of your messenger inbox",
    "minta pacar/sahabt/mantan/crush kamu buat nyanyiin reff lagu yang kamu suka",
    "nyanyi balonku ada lima lengkap",
    "nyanyi abang tukang bakso pakai huruf'O' lengkap",
)
